[package]
name = "fp-index"
version = "0.1.0"
edition = "2024"
license-file = "../../LICENSE"

[dependencies]
fp-types = { path = "../fp-types" }
serde = { workspace = true }
thiserror = { workspace = true }
